### ISSUE TITLE
Proposal: Sprite Groups

### ISSUE THREAD

**Issue by KallDrexx** [profexorgeek/Glade2d#10]
Today in Glade, each sprite has to be manually managed by the developer.  When sprites are related to each other, and should have the same physics, collision detection, and positioning rules applied to them

A concrete example of this is space invaders. In the game you have X rows and Y columns of enemies that all move in the same direction and at the same speed. They change animation frames at the exact same time.  They change direction whenever the outer ones hit the screen boundary, only one enemy on the bottom row fires at a time, and generally it's impossible for a player's shot to collide with an inside enemy before hitting an outside enemy.

Many NES games had larger bosses that were made up of multiple sprites combined together as well (though I don't have good examples offhand).

It seems like this can be made easier on developers with the concept of sprite groups, akin to entities in FRB.  This provides a central type that developers can inherit from to provide functionality to a group of sprites.  The developer can then just add the whole sprite group to the screen to add it to the screen graph.  

Sprite groups can be optionally rendered to a custom render target, which allows special cases where the whole group of sprites only has to be rendered once instead of every frame.

**Comment by profexorgeek** [comment]
I think this was accomplished by our `Layer` implementation so I'm closing this!
